"""
CivicBuzz Initial Database Seeder
Seeds initial Municipalities, Wards, Departments, Admin/Citizen accounts,
Participatory Projects, Tenders, and initial Complaints to match the frontend demo.
"""

import logging
from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from motor.motor_asyncio import AsyncIOMotorDatabase
from app.core.security import get_password_hash
from app.models.sql.user import User, UserRole
from app.models.sql.ward import Municipality, Ward
from app.models.sql.department import Department
from app.models.sql.project import Project, ProjectStatus, WardBudget, Tender, TenderStatus

logger = logging.getLogger("civicbuzz.db.seed")


async def seed_database(db: AsyncSession, mongo_db: AsyncIOMotorDatabase):
    """Seed initial data if tables/collections are empty."""
    # 1. Seed Municipality
    stmt_muni = select(Municipality)
    res_muni = await db.execute(stmt_muni)
    muni = res_muni.scalar_one_or_none()
    if not muni:
        muni = Municipality(
            name="Bhubaneswar Municipal Corporation",
            state="Odisha",
            city="Bhubaneswar",
            code="BMC-01",
        )
        db.add(muni)
        await db.flush()

    # 2. Seed Wards
    stmt_wards = select(Ward)
    res_wards = await db.execute(stmt_wards)
    existing_wards = res_wards.scalars().all()
    if not existing_wards:
        ward_data = [
            (1, "Ward 1 - Chandrasekharpur", 20.3241, 85.8152),
            (2, "Ward 2 - Patia Corridor", 20.3548, 85.8184),
            (3, "Ward 3 - Nayapalli", 20.2985, 85.8122),
            (4, "Ward 4 - Jayadev Vihar", 20.3012, 85.8234),
            (5, "Ward 5 - Riverside Park / Mancheswar", 20.3155, 85.8521),
            (6, "Ward 6 - Rasulgarh", 20.2912, 85.8641),
            (7, "Ward 7 - Saheed Nagar", 20.2891, 85.8432),
            (8, "Ward 8 - Market Corridor", 20.2741, 85.8362),
            (9, "Ward 9 - Unit 9 / Bapuji Nagar", 20.2684, 85.8315),
            (10, "Ward 10 - Ashok Nagar", 20.2621, 85.8412),
            (11, "Ward 11 - Old Town Heritage", 20.2412, 85.8341),
            (12, "Ward 12 - Janpath / College Gate", 20.2961, 85.8245),
            (13, "Ward 13 - Khandagiri", 20.2584, 85.7865),
            (14, "Ward 14 - Baramunda", 20.2792, 85.7981),
            (15, "Ward 15 - Infocity Road", 20.3491, 85.8082),
        ]
        for wnum, wname, lat, lng in ward_data:
            db.add(Ward(
                ward_number=wnum,
                ward_name=wname,
                municipality_id=muni.id,
                center_lat=lat,
                center_lng=lng,
                radius_meters=2500.0,
            ))
        await db.flush()

    # 3. Seed Departments
    stmt_dept = select(Department)
    res_dept = await db.execute(stmt_dept)
    if not res_dept.scalars().all():
        departments = [
            ("ROADS_AND_POTHOLES", "Roads & Potholes Department", "Maintains city roads, asphalt, potholes, footpaths", 24),
            ("GARBAGE_AND_SANITATION", "Garbage & Sanitation Department", "Handles waste collection, dumping sites, bins", 12),
            ("WATER_AND_DRAINAGE", "Water & Drainage Department", "Addresses pipe bursts, waterlogging, drain blockage", 24),
            ("STREET_LIGHTS_AND_ELECTRICITY", "Street Lighting & Electricity Department", "Repairs streetlights, fixtures, wiring", 24),
            ("PARKS_AND_PUBLIC_SPACES", "Parks & Public Spaces Department", "Maintains public parks, benches, playgrounds", 72),
            ("HEALTH_AND_STRAY_ANIMALS", "Public Health & Veterinary Department", "Sanitation vector control, stray animal management", 48),
        ]
        for code, name, desc, sla in departments:
            db.add(Department(code=code, name=name, description=desc, sla_hours=sla))
        await db.flush()

    # 4. Seed Admin and Citizen Users
    stmt_user = select(User).where(User.email == "admin@civicbuzz.in")
    res_user = await db.execute(stmt_user)
    if not res_user.scalar_one_or_none():
        admin_user = User(
            user_uid="USR-ADMIN-01",
            email="admin@civicbuzz.in",
            full_name="Aditya Kumar Shyam",
            hashed_password=get_password_hash("Admin@123"),
            role=UserRole.SUPER_ADMIN,
            is_active=True,
            is_verified=True,
        )
        db.add(admin_user)

    stmt_cit = select(User).where(User.email == "citizen@civicbuzz.in")
    res_cit = await db.execute(stmt_cit)
    if not res_cit.scalar_one_or_none():
        citizen_user = User(
            user_uid="USR-CITIZEN-01",
            email="citizen@civicbuzz.in",
            full_name="Aanya Sharma",
            hashed_password=get_password_hash("Citizen@123"),
            role=UserRole.CITIZEN,
            aadhaar_masked="XXXX-XXXX-8921",
            is_aadhaar_verified=True,
            is_active=True,
            is_verified=True,
        )
        db.add(citizen_user)
    await db.flush()

    # 5. Seed Participatory Budgeting Projects
    stmt_proj = select(Project)
    res_proj = await db.execute(stmt_proj)
    if not res_proj.scalars().all():
        projects = [
            ("Drainage improvement on School Road", "Clear blocked drains and build two covered storm segments near the primary school.", 12, "Drainage", 400000.0, 49, "💧", "School Road, Ward 12"),
            ("Install 20 LED streetlights", "Add energy-efficient LED streetlights around the market and school corridors for safety.", 8, "Lighting", 300000.0, 33, "💡", "Market Corridor, Ward 8"),
            ("Priority road patching", "Repair heavily damaged pothole segments across Ward 15 connecting to Infocity.", 15, "Roads", 250000.0, 21, "🛣️", "Infocity Road, Ward 15"),
        ]
        for idx, (title, desc, wid, cat, cost, votes, icon, loc) in enumerate(projects, start=1):
            db.add(Project(
                project_uid=f"PRJ-00{idx}",
                title=title,
                description=desc,
                ward_id=wid,
                category=cat,
                estimated_cost=cost,
                allocated_budget=cost,
                vote_count=votes,
                status=ProjectStatus.APPROVED,
                icon=icon,
                location_name=loc,
                linked_complaint_count=votes // 4,
            ))
        await db.flush()

    # 6. Seed Government Tenders
    stmt_tenders = select(Tender)
    res_tenders = await db.execute(stmt_tenders)
    if not res_tenders.scalars().all():
        tenders = [
            ("CB-T-0015", "Priority road patching — Ward 15", "Repair the most-reported pothole locations across Ward 15.", 15, "Roads & Potholes", "roads", "Ward 15", 250000.0, 30, 3, 21, TenderStatus.PUBLISHED, 2, 40),
            ("CB-T-0018", "Drainage improvement — School Road", "Clear blocked drains and improve two drainage segments near primary school.", 12, "Water & Drainage", "drainage", "Ward 12", 400000.0, 45, 4, 49, TenderStatus.PUBLISHED, 1, 20),
            ("CB-T-0012", "Install 20 LED streetlights", "Add or replace streetlights around the market and school corridors.", 8, "Street Lights", "lighting", "Ward 8", 300000.0, 30, 2, 33, TenderStatus.IN_PROGRESS, 3, 72),
            ("CB-T-0009", "Market sanitation upgrade", "Improve waste collection points and sanitation facilities near the market.", 9, "Garbage & Sanitation", "sanitation", "Ward 9", 180000.0, 20, 5, 18, TenderStatus.COMPLETED, 5, 100),
        ]
        for tid, title, desc, wid, dept, cat, loc, budget, dur, locs, votes, status, stage, prog in tenders:
            db.add(Tender(
                tender_id=tid,
                title=title,
                description=desc,
                ward_id=wid,
                department_name=dept,
                category=cat,
                location=loc,
                estimated_budget=budget,
                duration_days=dur,
                verified_locations_count=locs,
                community_votes=votes,
                status=status,
                stage_progress=stage,
                progress_percentage=prog,
            ))
        await db.flush()

    await db.commit()

    # 7. Seed Initial Complaints in MongoDB (10 realistic Bhubaneswar issues)
    complaint_count = await mongo_db.complaints.count_documents({})
    if complaint_count == 0:
        now_str = datetime.now(timezone.utc).isoformat()
        demo_complaints = [
            {
                "complaint_id": "CB-BHUB-1042",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Deep crater-sized pothole near KIIT Square",
                "description": "Large pothole causing vehicle damage and traffic hazards near KIIT Campus 6 road.",
                "category": "ROADS",
                "sub_category": "POTHOLE",
                "location": {
                    "latitude": 20.3533,
                    "longitude": 85.8189,
                    "address": "KIIT Square, Patia Main Road, Bhubaneswar",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 1,
                    "ward_name": "Ward 1 (Patia & KIIT)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8189, 20.3533]},
                "status": "IN_PROGRESS",
                "department_code": "ROADS_AND_POTHOLES",
                "department_name": "Roads & Works Department",
                "severity": "CRITICAL",
                "priority": {"score": 94.0, "level": "CRITICAL", "reasons": ["High traffic hazard near educational institution", "5 duplicate reports"]},
                "ai_analysis": {"category": "ROADS", "sub_category": "POTHOLE", "severity": "CRITICAL", "summary": "Deep asphalt cavity causing traffic slowdown and collision risks", "recommended_department": "ROADS_AND_POTHOLES", "confidence": 0.96, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": True, "duplicate_score": 0.89, "cluster_count": 5, "related_complaint_ids": ["CB-0143", "CB-0144"]},
                "image_url": "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
                "evidence": [{"evidence_id": "EVD-1042-1", "evidence_type": "BEFORE_IMAGE", "file_url": "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80", "timestamp": now_str}],
                "timeline": [
                    {"step": "Reported by Citizen", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance registered with GPS coordinates."},
                    {"step": "AI Triage & Urgency Ranked", "status": "ASSIGNED", "timestamp": now_str, "actor_role": "AI_SYSTEM", "notes": "Severity evaluated as CRITICAL (94/100). Routed to Roads & Works."},
                    {"step": "Crew Dispatched", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "BMC Road maintenance squad on site for asphalt patching."},
                ],
                "upvotes": 42,
                "sla_hours": 48,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1043",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Blocked stormwater drain causing waterlogging in Patia",
                "description": "Debris and plastic waste blocking primary stormwater culvert, causing road flooding during rain.",
                "category": "DRAINAGE",
                "sub_category": "BLOCKED_DRAIN",
                "location": {
                    "latitude": 20.3548,
                    "longitude": 85.8184,
                    "address": "Near Infocity Square, Patia Corridor",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 2,
                    "ward_name": "Ward 2 (Patia Corridor)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.94,
                },
                "location_point": {"type": "Point", "coordinates": [85.8184, 20.3548]},
                "status": "SUBMITTED",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "HIGH",
                "priority": {"score": 82.0, "level": "HIGH", "reasons": ["Risk of street submergence and vector breeding"]},
                "ai_analysis": {"category": "DRAINAGE", "sub_category": "BLOCKED_DRAIN", "severity": "HIGH", "summary": "Heavy debris clogging main rainwater discharge line", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.92, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [{"step": "Reported by Citizen", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance received. Awaiting department triage."}],
                "upvotes": 18,
                "sla_hours": 24,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1044",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Broken high-mast streetlight pole in Saheed Nagar",
                "description": "Streetlight fixture completely non-functional for 4 consecutive nights, creating dark danger zone.",
                "category": "LIGHTING",
                "sub_category": "BROKEN_LIGHT",
                "location": {
                    "latitude": 20.2905,
                    "longitude": 85.8450,
                    "address": "Saheed Nagar Main Market, Ward 7",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 7,
                    "ward_name": "Ward 7 (Saheed Nagar)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.95,
                },
                "location_point": {"type": "Point", "coordinates": [85.8450, 20.2905]},
                "status": "RESOLVED",
                "department_code": "STREET_LIGHTS_AND_ELECTRICITY",
                "department_name": "Street Lighting & Electricity",
                "severity": "HIGH",
                "priority": {"score": 80.0, "level": "HIGH", "reasons": ["Night commuter safety risk"]},
                "ai_analysis": {"category": "LIGHTING", "sub_category": "BROKEN_LIGHT", "severity": "HIGH", "summary": "Unlit corridor creating night pedestrian hazard", "recommended_department": "STREET_LIGHTS_AND_ELECTRICITY", "confidence": 0.93, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [{"evidence_id": "EVD-1044-1", "evidence_type": "BEFORE_IMAGE", "file_url": "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80", "timestamp": now_str}],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Reported dark streetlight."},
                    {"step": "Repaired & New LED installed", "status": "READY_FOR_CITIZEN_VERIFICATION", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Bulb replaced by Electrical maintenance crew."},
                    {"step": "Citizen Confirmed & Resolved", "status": "RESOLVED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Resolution confirmed by citizen verification."},
                ],
                "upvotes": 29,
                "sla_hours": 24,
                "citizen_confirmed_resolved": True,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1045",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Overflowing garbage accumulation near Market Building",
                "description": "Solid waste overflowing on pedestrian walkways with severe foul odor and stray animals.",
                "category": "SANITATION",
                "sub_category": "GARBAGE_DUMP",
                "location": {
                    "latitude": 20.2741,
                    "longitude": 85.8362,
                    "address": "Market Building Corridor, Ward 8",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 8,
                    "ward_name": "Ward 8 (Market Corridor)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8362, 20.2741]},
                "status": "IN_PROGRESS",
                "department_code": "GARBAGE_AND_SANITATION",
                "department_name": "Garbage & Sanitation Department",
                "severity": "HIGH",
                "priority": {"score": 78.0, "level": "HIGH", "reasons": ["Public health hazard in commercial zone"]},
                "ai_analysis": {"category": "SANITATION", "sub_category": "GARBAGE_DUMP", "severity": "HIGH", "summary": "Waste bin overflow causing hygiene violation", "recommended_department": "GARBAGE_AND_SANITATION", "confidence": 0.95, "safety_risk_identified": False},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=800&q=80",
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance filed with photo evidence."},
                    {"step": "Waste Clearance Team Dispatched", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Compactor truck assigned for disposal."},
                ],
                "upvotes": 35,
                "sla_hours": 24,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1046",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Drinking water pipeline leak near Chandrasekharpur",
                "description": "Main drinking water pipeline cracked, flooding street and reducing water pressure to households.",
                "category": "WATER",
                "sub_category": "PIPE_LEAK",
                "location": {
                    "latitude": 20.3241,
                    "longitude": 85.8152,
                    "address": "Damana Square, Chandrasekharpur, Ward 1",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 1,
                    "ward_name": "Ward 1 (Chandrasekharpur)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.97,
                },
                "location_point": {"type": "Point", "coordinates": [85.8152, 20.3241]},
                "status": "ASSIGNED",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "CRITICAL",
                "priority": {"score": 92.0, "level": "CRITICAL", "reasons": ["Pressurized clean water loss and basement inundation"]},
                "ai_analysis": {"category": "WATER", "sub_category": "PIPE_LEAK", "severity": "CRITICAL", "summary": "Ruptured supply main discharging drinking water onto pavement", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.98, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Emergency water leak logged."},
                    {"step": "Assigned to WATCO Hydro Division", "status": "ASSIGNED", "timestamp": now_str, "actor_role": "AI_SYSTEM", "notes": "Priority ticket dispatched to field engineers."},
                ],
                "upvotes": 53,
                "sla_hours": 12,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1047",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Damaged pedestrian footpath near Khandagiri Caves",
                "description": "Broken paving slabs and exposed concrete rebar on tourist pedestrian walkway.",
                "category": "INFRASTRUCTURE",
                "sub_category": "DAMAGED_SIDEWALK",
                "location": {
                    "latitude": 20.2584,
                    "longitude": 85.7865,
                    "address": "Khandagiri Caves Entrance, Jagamara Road, Ward 13",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 13,
                    "ward_name": "Ward 13 (Khandagiri)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.93,
                },
                "location_point": {"type": "Point", "coordinates": [85.7865, 20.2584]},
                "status": "SUBMITTED",
                "department_code": "ROADS_AND_POTHOLES",
                "department_name": "Roads & Works Department",
                "severity": "MEDIUM",
                "priority": {"score": 62.0, "level": "MEDIUM", "reasons": ["Footpath trip hazard near heritage tourist spot"]},
                "ai_analysis": {"category": "INFRASTRUCTURE", "sub_category": "DAMAGED_SIDEWALK", "severity": "MEDIUM", "summary": "Damaged sidewalk tiles requiring repaving", "recommended_department": "ROADS_AND_POTHOLES", "confidence": 0.89, "safety_risk_identified": False},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [{"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Reported by citizen."}],
                "upvotes": 14,
                "sla_hours": 72,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1048",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Overflowing sewer drain in Old Town",
                "description": "Sewage discharge leaking from open drain near heritage temple corridor.",
                "category": "DRAINAGE",
                "sub_category": "SEWAGE_LEAK",
                "location": {
                    "latitude": 20.2412,
                    "longitude": 85.8341,
                    "address": "Bindu Sagar Road, Old Town, Ward 11",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 11,
                    "ward_name": "Ward 11 (Old Town Heritage)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8341, 20.2412]},
                "status": "IN_PROGRESS",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "CRITICAL",
                "priority": {"score": 91.0, "level": "CRITICAL", "reasons": ["Public health violation near religious water body"]},
                "ai_analysis": {"category": "DRAINAGE", "sub_category": "SEWAGE_LEAK", "severity": "CRITICAL", "summary": "Unsealed sewage drain requiring immediate suction cleaning", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.95, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Urgent sanitation defect logged."},
                    {"step": "Suction Tanker Dispatched", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "BMC Drainage squad addressing blockage."},
                ],
                "upvotes": 61,
                "sla_hours": 18,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1049",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Broken park swing and damaged bench in BDA Community Park",
                "description": "Children playground swing chains broken and metal bench detached from concrete base.",
                "category": "PARKS",
                "sub_category": "BROKEN_EQUIPMENT",
                "location": {
                    "latitude": 20.3155,
                    "longitude": 85.8521,
                    "address": "BDA Community Park, Mancheswar, Ward 5",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 5,
                    "ward_name": "Ward 5 (Mancheswar)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.91,
                },
                "location_point": {"type": "Point", "coordinates": [85.8521, 20.3155]},
                "status": "RESOLVED",
                "department_code": "PARKS_AND_PUBLIC_SPACES",
                "department_name": "Parks & Public Spaces",
                "severity": "LOW",
                "priority": {"score": 45.0, "level": "LOW", "reasons": ["Community recreational equipment repair"]},
                "ai_analysis": {"category": "PARKS", "sub_category": "BROKEN_EQUIPMENT", "severity": "LOW", "summary": "Playground equipment maintenance needed", "recommended_department": "PARKS_AND_PUBLIC_SPACES", "confidence": 0.88, "safety_risk_identified": False},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Reported by citizen."},
                    {"step": "Equipment welded and repainted", "status": "RESOLVED", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Repaired and verified safe."},
                ],
                "upvotes": 8,
                "sla_hours": 72,
                "citizen_confirmed_resolved": True,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1050",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Severe road asphalt damage near Rasulgarh Overbridge",
                "description": "Heavy vehicle traffic caused multiple deep asphalt fissures and loose gravel on service road.",
                "category": "ROADS",
                "sub_category": "ROAD_SURFACE",
                "location": {
                    "latitude": 20.2912,
                    "longitude": 85.8641,
                    "address": "Rasulgarh Square Service Lane, Ward 6",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 6,
                    "ward_name": "Ward 6 (Rasulgarh)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.95,
                },
                "location_point": {"type": "Point", "coordinates": [85.8641, 20.2912]},
                "status": "ASSIGNED",
                "department_code": "ROADS_AND_POTHOLES",
                "department_name": "Roads & Works Department",
                "severity": "HIGH",
                "priority": {"score": 76.0, "level": "HIGH", "reasons": ["National Highway connecting corridor"]},
                "ai_analysis": {"category": "ROADS", "sub_category": "ROAD_SURFACE", "severity": "HIGH", "summary": "Asphalt degradation causing skidding risk for two-wheelers", "recommended_department": "ROADS_AND_POTHOLES", "confidence": 0.94, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Logged with photo evidence."},
                    {"step": "Assigned to Ward 6 Road Cell", "status": "ASSIGNED", "timestamp": now_str, "actor_role": "AI_SYSTEM", "notes": "Scheduled for road roller resurfacing."},
                ],
                "upvotes": 22,
                "sla_hours": 48,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-BHUB-1051",
                "user_id": 2,
                "complainant_name": "Aanya Sharma",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Severe monsoon waterlogging near Jayadev Vihar Junction",
                "description": "Water accumulation over 1.5 feet deep halting vehicle traffic near Jayadev Vihar flyover.",
                "category": "DRAINAGE",
                "sub_category": "WATERLOGGING",
                "location": {
                    "latitude": 20.3012,
                    "longitude": 85.8234,
                    "address": "Jayadev Vihar Overbridge, Ward 4",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 4,
                    "ward_name": "Ward 4 (Jayadev Vihar)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8234, 20.3012]},
                "status": "IN_PROGRESS",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "CRITICAL",
                "priority": {"score": 96.0, "level": "CRITICAL", "reasons": ["Major arterial junction blockage during monsoon"]},
                "ai_analysis": {"category": "DRAINAGE", "sub_category": "WATERLOGGING", "severity": "CRITICAL", "summary": "Severe street inundation requiring emergency drainage pumps", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.97, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Emergency traffic waterlogging reported."},
                    {"step": "Mobile Dewatering Pump Deployed", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Emergency pumping in progress."},
                ],
                "upvotes": 74,
                "sla_hours": 12,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12480",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Dangerous deep pothole cavity on Janpath Road",
                "description": "Large dangerous asphalt pothole near Ram Mandir / College Gate causing accidents and wheel damage.",
                "category": "ROADS",
                "sub_category": "POTHOLE",
                "location": {
                    "latitude": 20.2961,
                    "longitude": 85.8245,
                    "address": "Janpath Road, near College Gate, Ward 12",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 12,
                    "ward_name": "Ward 12 (Janpath / College Gate)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.98,
                },
                "location_point": {"type": "Point", "coordinates": [85.8245, 20.2961]},
                "status": "IN_PROGRESS",
                "department_code": "ROADS_AND_POTHOLES",
                "department_name": "Roads & Works Department",
                "severity": "CRITICAL",
                "priority": {"score": 92.0, "level": "CRITICAL", "reasons": ["High traffic hazard on arterial avenue", "SLA threshold critical"]},
                "ai_analysis": {"category": "ROADS", "sub_category": "POTHOLE", "severity": "CRITICAL", "summary": "Deep road depression requiring immediate asphalt cold-mix patching", "recommended_department": "ROADS_AND_POTHOLES", "confidence": 0.98, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
                "evidence": [{"evidence_id": "EVD-12480-1", "evidence_type": "BEFORE_IMAGE", "file_url": "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80", "timestamp": now_str}],
                "timeline": [
                    {"step": "Reported by Citizen", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance registered with GPS coordinates."},
                    {"step": "AI Triage & Urgency Ranked", "status": "ASSIGNED", "timestamp": now_str, "actor_role": "AI_SYSTEM", "notes": "Ranked CRITICAL (92/100). Routed to Ward 12 Road Cell."},
                    {"step": "Field Team Dispatched", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "BMC Road maintenance squad dispatched on site."},
                ],
                "upvotes": 38,
                "sla_hours": 24,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12481",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Overflowing Community Garbage Dump near Park",
                "description": "Garbage container spilling onto the walkway near Jayadev Vihar Community Park causing foul smell and health hazard.",
                "category": "SANITATION",
                "sub_category": "OVERFLOWING_BIN",
                "location": {
                    "latitude": 20.3012,
                    "longitude": 85.8234,
                    "address": "Community Park Entrance, Jayadev Vihar, Ward 4",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 4,
                    "ward_name": "Ward 4 (Jayadev Vihar)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.95,
                },
                "location_point": {"type": "Point", "coordinates": [85.8234, 20.3012]},
                "status": "ASSIGNED",
                "department_code": "GARBAGE_AND_SANITATION",
                "department_name": "Garbage & Sanitation Department",
                "severity": "HIGH",
                "priority": {"score": 84.0, "level": "HIGH", "reasons": ["Public park foot traffic health risk"]},
                "ai_analysis": {"category": "SANITATION", "sub_category": "OVERFLOWING_BIN", "severity": "HIGH", "summary": "Uncleared solid municipal waste container", "recommended_department": "GARBAGE_AND_SANITATION", "confidence": 0.94, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80",
                "evidence": [],
                "timeline": [
                    {"step": "Reported by Citizen", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance submitted with photo evidence."},
                    {"step": "Routed to Sanitation", "status": "ASSIGNED", "timestamp": now_str, "actor_role": "AI_SYSTEM", "notes": "Assigned to Ward 4 Sanitation Truck Team."},
                ],
                "upvotes": 25,
                "sla_hours": 24,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12482",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Main Water Supply Pipeline Leakage",
                "description": "High pressure potable water leaking onto street from cracked underground main line in Patia.",
                "category": "WATER_SUPPLY",
                "sub_category": "PIPE_BURST",
                "location": {
                    "latitude": 20.3548,
                    "longitude": 85.8184,
                    "address": "Near Infocity Square, Patia Corridor, Ward 2",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 2,
                    "ward_name": "Ward 2 (Patia Corridor)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8184, 20.3548]},
                "status": "IN_PROGRESS",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "HIGH",
                "priority": {"score": 86.0, "level": "HIGH", "reasons": ["Clean drinking water wastage"]},
                "ai_analysis": {"category": "WATER_SUPPLY", "sub_category": "PIPE_BURST", "severity": "HIGH", "summary": "Pressurized main line fracture requiring pipeline replacement", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.96, "safety_risk_identified": False},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80",
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Leakage reported."},
                    {"step": "Plumbing Crew on Site", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Water supply line isolated for weld repair."},
                ],
                "upvotes": 31,
                "sla_hours": 36,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12483",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Blocked Stormwater Drain near College Gate",
                "description": "Concrete culvert completely blocked with silt, threatening street flooding during rains.",
                "category": "DRAINAGE",
                "sub_category": "BLOCKED_DRAIN",
                "location": {
                    "latitude": 20.2961,
                    "longitude": 85.8245,
                    "address": "College Gate, Janpath, Ward 12",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 12,
                    "ward_name": "Ward 12 (Janpath / College Gate)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.97,
                },
                "location_point": {"type": "Point", "coordinates": [85.8245, 20.2961]},
                "status": "IN_PROGRESS",
                "department_code": "WATER_AND_DRAINAGE",
                "department_name": "Water & Drainage Department",
                "severity": "CRITICAL",
                "priority": {"score": 90.0, "level": "CRITICAL", "reasons": ["Monsoon vulnerability zone"]},
                "ai_analysis": {"category": "DRAINAGE", "sub_category": "BLOCKED_DRAIN", "severity": "CRITICAL", "summary": "Heavy sediment block in roadside culvert", "recommended_department": "WATER_AND_DRAINAGE", "confidence": 0.95, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80",
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Reported drainage blockage."},
                    {"step": "De-silting Crew Active", "status": "IN_PROGRESS", "timestamp": now_str, "actor_role": "OFFICER", "notes": "JCB & manual de-silting crew clearing line."},
                ],
                "upvotes": 49,
                "sla_hours": 24,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12484",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": True,
                "title": "Flickering & Broken Streetlights on Infocity Road",
                "description": "3 consecutive LED streetlight poles non-functional near Infocity IT corridor.",
                "category": "LIGHTING",
                "sub_category": "BROKEN_LIGHT",
                "location": {
                    "latitude": 20.3491,
                    "longitude": 85.8082,
                    "address": "Infocity Road, Ward 15",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 15,
                    "ward_name": "Ward 15 (Infocity Road)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.94,
                },
                "location_point": {"type": "Point", "coordinates": [85.8082, 20.3491]},
                "status": "SUBMITTED",
                "department_code": "STREET_LIGHTS_AND_ELECTRICITY",
                "department_name": "Street Lighting & Electricity",
                "severity": "MEDIUM",
                "priority": {"score": 68.0, "level": "MEDIUM", "reasons": ["Evening commuter visibility"]},
                "ai_analysis": {"category": "LIGHTING", "sub_category": "BROKEN_LIGHT", "severity": "MEDIUM", "summary": "Damaged streetlight fixture requiring driver and lamp replacement", "recommended_department": "STREET_LIGHTS_AND_ELECTRICITY", "confidence": 0.93, "safety_risk_identified": False},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": None,
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Grievance logged by citizen."},
                ],
                "upvotes": 12,
                "sla_hours": 48,
                "citizen_confirmed_resolved": False,
                "created_at": now_str,
                "updated_at": now_str,
            },
            {
                "complaint_id": "CB-12479",
                "user_id": 2,
                "complainant_name": "Verified Citizen",
                "complainant_email": "citizen@civicbuzz.in",
                "is_anonymous": False,
                "title": "Dark Stretch — Non-functional High-Mast Light",
                "description": "High-mast tower at Market Corridor junction was dark for 2 days. Repaired and verified.",
                "category": "LIGHTING",
                "sub_category": "BROKEN_LIGHT",
                "location": {
                    "latitude": 20.2741,
                    "longitude": 85.8362,
                    "address": "Market Corridor Square, Ward 8",
                    "city": "Bhubaneswar",
                    "municipality": "Bhubaneswar Municipal Corporation",
                    "ward_id": 8,
                    "ward_name": "Ward 8 (Market Corridor)",
                    "source": "GPS_PINPOINT",
                    "location_confidence": 0.96,
                },
                "location_point": {"type": "Point", "coordinates": [85.8362, 20.2741]},
                "status": "RESOLVED",
                "department_code": "STREET_LIGHTS_AND_ELECTRICITY",
                "department_name": "Street Lighting & Electricity",
                "severity": "HIGH",
                "priority": {"score": 78.0, "level": "HIGH", "reasons": ["Busy evening market square"]},
                "ai_analysis": {"category": "LIGHTING", "sub_category": "BROKEN_LIGHT", "severity": "HIGH", "summary": "High mast capacitor failure", "recommended_department": "STREET_LIGHTS_AND_ELECTRICITY", "confidence": 0.95, "safety_risk_identified": True},
                "duplicate_info": {"is_duplicate": False, "duplicate_score": 0.0, "cluster_count": 1, "related_complaint_ids": []},
                "image_url": "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80",
                "evidence": [],
                "timeline": [
                    {"step": "Reported", "status": "SUBMITTED", "timestamp": now_str, "actor_role": "CITIZEN", "notes": "Reported non-functional light."},
                    {"step": "Repaired & Verified", "status": "RESOLVED", "timestamp": now_str, "actor_role": "OFFICER", "notes": "Capacitor replaced. Verified operational by 2 residents."},
                ],
                "upvotes": 27,
                "sla_hours": 24,
                "citizen_confirmed_resolved": True,
                "created_at": now_str,
                "updated_at": now_str,
            }
        ]
        for comp in demo_complaints:
            existing_doc = await mongo_db.complaints.find_one({"complaint_id": comp["complaint_id"]})
            if not existing_doc:
                await mongo_db.complaints.insert_one(comp)

    logger.info("Database seeding completed successfully.")
