"""
CivicBuzz Schemas Export
"""

from app.schemas.common import APIResponse, PaginatedResponse
from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    TokenResponse,
    SendOTPRequest,
    VerifyOTPRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    AadhaarInitiateRequest,
    AadhaarVerifyRequest,
    UserProfileResponse,
)
from app.schemas.complaint import (
    ComplaintCreateRequest,
    ComplaintUpdateRequest,
    ComplaintStatusUpdateRequest,
    ComplaintAssignRequest,
    CitizenDisputeRequest,
    ComplaintDetailResponse,
    PublicComplaintResponse,
)
from app.schemas.location import (
    LocationResolveRequest,
    LocationResolveResponse,
    WardResponse,
)
from app.schemas.evidence import (
    EvidenceUploadResponse,
    EvidenceVerifyRequest,
    ChatMessageRequest,
    ChatMessageResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ProjectRankingResponse,
    TenderCreateRequest,
    TenderUpdateRequest,
    TenderResponse,
    VoteRequest,
    VoteResponse,
    AdminDashboardStatsResponse,
    ContactSubmitRequest,
    ContactResponse,
)

__all__ = [
    "APIResponse",
    "PaginatedResponse",
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenResponse",
    "SendOTPRequest",
    "VerifyOTPRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "AadhaarInitiateRequest",
    "AadhaarVerifyRequest",
    "UserProfileResponse",
    "ComplaintCreateRequest",
    "ComplaintUpdateRequest",
    "ComplaintStatusUpdateRequest",
    "ComplaintAssignRequest",
    "CitizenDisputeRequest",
    "ComplaintDetailResponse",
    "PublicComplaintResponse",
    "LocationResolveRequest",
    "LocationResolveResponse",
    "WardResponse",
    "EvidenceUploadResponse",
    "EvidenceVerifyRequest",
    "ChatMessageRequest",
    "ChatMessageResponse",
    "ProjectCreateRequest",
    "ProjectResponse",
    "ProjectRankingResponse",
    "TenderCreateRequest",
    "TenderUpdateRequest",
    "TenderResponse",
    "VoteRequest",
    "VoteResponse",
    "AdminDashboardStatsResponse",
    "ContactSubmitRequest",
    "ContactResponse",
]
